(ns hbm_memory.actor
  "hbm_memory clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). HBM stack design / 3D TSV memory manufacture.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; MemoryStack
   {:db/ident :hbm_memory.MemoryStack/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.MemoryStack/partNumber :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/heightDie :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/capacityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/bandwidthGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryStack/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; DramDie
   {:db/ident :hbm_memory.DramDie/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.DramDie/stackId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.DramDie/processNode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.DramDie/capacityGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.DramDie/knownGoodDie :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.DramDie/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.DramDie/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ThroughSiliconVia
   {:db/ident :hbm_memory.ThroughSiliconVia/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.ThroughSiliconVia/stackId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.ThroughSiliconVia/count :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.ThroughSiliconVia/pitchUm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.ThroughSiliconVia/aspectRatio :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.ThroughSiliconVia/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.ThroughSiliconVia/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemoryChannel
   {:db/ident :hbm_memory.MemoryChannel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.MemoryChannel/stackId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryChannel/width :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryChannel/pseudoChannels :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryChannel/dataRateGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryChannel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.MemoryChannel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; RefreshPolicy
   {:db/ident :hbm_memory.RefreshPolicy/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.RefreshPolicy/stackId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.RefreshPolicy/mode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.RefreshPolicy/intervalNs :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.RefreshPolicy/temperatureC :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.RefreshPolicy/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.RefreshPolicy/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TestBin
   {:db/ident :hbm_memory.TestBin/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :hbm_memory.TestBin/stackId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.TestBin/binCode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.TestBin/yield :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.TestBin/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.TestBin/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :hbm_memory.TestBin/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"MemoryStack" "DramDie" "ThroughSiliconVia" "MemoryChannel" "RefreshPolicy" "TestBin"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "hbm_memory: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "hbm_memory: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "hbm_memory: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── MemoryStack ────────────────────────────────────────────────────────────────
(defn create-memory-stack
  "Create a MemoryStack."
  [port data]
  (require-fields data ["partNumber" "generation"])
  (let [id (new-id "hbm_mem")
        e {:db/id id
           :hbm_memory.MemoryStack/id id
           :hbm_memory.MemoryStack/partNumber (get data :partNumber)
           :hbm_memory.MemoryStack/generation (get data :generation)
           :hbm_memory.MemoryStack/heightDie (as-long (get data :heightDie))
           :hbm_memory.MemoryStack/capacityGb (as-long (get data :capacityGb))
           :hbm_memory.MemoryStack/bandwidthGbps (as-double (get data :bandwidthGbps))
           :hbm_memory.MemoryStack/createdAt (now)
           :hbm_memory.MemoryStack/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-stacks
  "List MemoryStack with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-stacks port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.MemoryStack/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.MemoryStack/partNumber :hbm_memory.MemoryStack/generation :hbm_memory.MemoryStack/heightDie :hbm_memory.MemoryStack/capacityGb :hbm_memory.MemoryStack/bandwidthGbps])]
     (paginate rows opts))))

(defn get-memory-stack
  "Retrieve a MemoryStack by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-stack port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-memory-stack
  "Update a MemoryStack; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :partNumber) (conj [:db/add id :hbm_memory.MemoryStack/partNumber (get data :partNumber)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :hbm_memory.MemoryStack/generation (get data :generation)]))
                   (cond-> (contains? data :heightDie) (conj [:db/add id :hbm_memory.MemoryStack/heightDie (as-long (get data :heightDie))]))
                   (cond-> (contains? data :capacityGb) (conj [:db/add id :hbm_memory.MemoryStack/capacityGb (as-long (get data :capacityGb))]))
                   (cond-> (contains? data :bandwidthGbps) (conj [:db/add id :hbm_memory.MemoryStack/bandwidthGbps (as-double (get data :bandwidthGbps))]))
                   (conj [:db/add id :hbm_memory.MemoryStack/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-stack
  "Delete a MemoryStack."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── DramDie ────────────────────────────────────────────────────────────────
(defn create-dram-die
  "Create a DramDie."
  [port data]
  (require-fields data ["processNode" "capacityGb"])
  (let [id (new-id "hbm_dra")
        e {:db/id id
           :hbm_memory.DramDie/id id
           :hbm_memory.DramDie/stackId (get data :stackId)
           :hbm_memory.DramDie/processNode (get data :processNode)
           :hbm_memory.DramDie/capacityGb (as-long (get data :capacityGb))
           :hbm_memory.DramDie/knownGoodDie (as-bool (get data :knownGoodDie))
           :hbm_memory.DramDie/createdAt (now)
           :hbm_memory.DramDie/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-dram-dies
  "List DramDie with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-dram-dies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.DramDie/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.DramDie/stackId :hbm_memory.DramDie/processNode :hbm_memory.DramDie/capacityGb :hbm_memory.DramDie/knownGoodDie])]
     (paginate rows opts))))

(defn get-dram-die
  "Retrieve a DramDie by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-dram-die port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-dram-die
  "Update a DramDie; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stackId) (conj [:db/add id :hbm_memory.DramDie/stackId (get data :stackId)]))
                   (cond-> (contains? data :processNode) (conj [:db/add id :hbm_memory.DramDie/processNode (get data :processNode)]))
                   (cond-> (contains? data :capacityGb) (conj [:db/add id :hbm_memory.DramDie/capacityGb (as-long (get data :capacityGb))]))
                   (cond-> (contains? data :knownGoodDie) (conj [:db/add id :hbm_memory.DramDie/knownGoodDie (as-bool (get data :knownGoodDie))]))
                   (conj [:db/add id :hbm_memory.DramDie/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-dram-die
  "Delete a DramDie."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ThroughSiliconVia ────────────────────────────────────────────────────────────────
(defn create-through-silicon-via
  "Create a ThroughSiliconVia."
  [port data]
  (require-fields data ["count" "pitchUm"])
  (let [id (new-id "hbm_thr")
        e {:db/id id
           :hbm_memory.ThroughSiliconVia/id id
           :hbm_memory.ThroughSiliconVia/stackId (get data :stackId)
           :hbm_memory.ThroughSiliconVia/count (as-long (get data :count))
           :hbm_memory.ThroughSiliconVia/pitchUm (as-double (get data :pitchUm))
           :hbm_memory.ThroughSiliconVia/aspectRatio (as-double (get data :aspectRatio))
           :hbm_memory.ThroughSiliconVia/createdAt (now)
           :hbm_memory.ThroughSiliconVia/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-through-silicon-vias
  "List ThroughSiliconVia with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-through-silicon-vias port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.ThroughSiliconVia/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.ThroughSiliconVia/stackId :hbm_memory.ThroughSiliconVia/count :hbm_memory.ThroughSiliconVia/pitchUm :hbm_memory.ThroughSiliconVia/aspectRatio])]
     (paginate rows opts))))

(defn get-through-silicon-via
  "Retrieve a ThroughSiliconVia by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-through-silicon-via port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-through-silicon-via
  "Update a ThroughSiliconVia; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stackId) (conj [:db/add id :hbm_memory.ThroughSiliconVia/stackId (get data :stackId)]))
                   (cond-> (contains? data :count) (conj [:db/add id :hbm_memory.ThroughSiliconVia/count (as-long (get data :count))]))
                   (cond-> (contains? data :pitchUm) (conj [:db/add id :hbm_memory.ThroughSiliconVia/pitchUm (as-double (get data :pitchUm))]))
                   (cond-> (contains? data :aspectRatio) (conj [:db/add id :hbm_memory.ThroughSiliconVia/aspectRatio (as-double (get data :aspectRatio))]))
                   (conj [:db/add id :hbm_memory.ThroughSiliconVia/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-through-silicon-via
  "Delete a ThroughSiliconVia."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemoryChannel ────────────────────────────────────────────────────────────────
(defn create-memory-channel
  "Create a MemoryChannel."
  [port data]
  (require-fields data ["width" "pseudoChannels"])
  (let [id (new-id "hbm_mem")
        e {:db/id id
           :hbm_memory.MemoryChannel/id id
           :hbm_memory.MemoryChannel/stackId (get data :stackId)
           :hbm_memory.MemoryChannel/width (as-long (get data :width))
           :hbm_memory.MemoryChannel/pseudoChannels (as-long (get data :pseudoChannels))
           :hbm_memory.MemoryChannel/dataRateGbps (as-double (get data :dataRateGbps))
           :hbm_memory.MemoryChannel/createdAt (now)
           :hbm_memory.MemoryChannel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-channels
  "List MemoryChannel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-channels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.MemoryChannel/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.MemoryChannel/stackId :hbm_memory.MemoryChannel/width :hbm_memory.MemoryChannel/pseudoChannels :hbm_memory.MemoryChannel/dataRateGbps])]
     (paginate rows opts))))

(defn get-memory-channel
  "Retrieve a MemoryChannel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-channel port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-memory-channel
  "Update a MemoryChannel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stackId) (conj [:db/add id :hbm_memory.MemoryChannel/stackId (get data :stackId)]))
                   (cond-> (contains? data :width) (conj [:db/add id :hbm_memory.MemoryChannel/width (as-long (get data :width))]))
                   (cond-> (contains? data :pseudoChannels) (conj [:db/add id :hbm_memory.MemoryChannel/pseudoChannels (as-long (get data :pseudoChannels))]))
                   (cond-> (contains? data :dataRateGbps) (conj [:db/add id :hbm_memory.MemoryChannel/dataRateGbps (as-double (get data :dataRateGbps))]))
                   (conj [:db/add id :hbm_memory.MemoryChannel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-channel
  "Delete a MemoryChannel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── RefreshPolicy ────────────────────────────────────────────────────────────────
(defn create-refresh-policy
  "Create a RefreshPolicy."
  [port data]
  (require-fields data ["mode" "intervalNs"])
  (let [id (new-id "hbm_ref")
        e {:db/id id
           :hbm_memory.RefreshPolicy/id id
           :hbm_memory.RefreshPolicy/stackId (get data :stackId)
           :hbm_memory.RefreshPolicy/mode (get data :mode)
           :hbm_memory.RefreshPolicy/intervalNs (as-double (get data :intervalNs))
           :hbm_memory.RefreshPolicy/temperatureC (as-double (get data :temperatureC))
           :hbm_memory.RefreshPolicy/createdAt (now)
           :hbm_memory.RefreshPolicy/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-refresh-policies
  "List RefreshPolicy with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-refresh-policies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.RefreshPolicy/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.RefreshPolicy/stackId :hbm_memory.RefreshPolicy/mode :hbm_memory.RefreshPolicy/intervalNs :hbm_memory.RefreshPolicy/temperatureC])]
     (paginate rows opts))))

(defn get-refresh-policy
  "Retrieve a RefreshPolicy by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-refresh-policy port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-refresh-policy
  "Update a RefreshPolicy; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stackId) (conj [:db/add id :hbm_memory.RefreshPolicy/stackId (get data :stackId)]))
                   (cond-> (contains? data :mode) (conj [:db/add id :hbm_memory.RefreshPolicy/mode (get data :mode)]))
                   (cond-> (contains? data :intervalNs) (conj [:db/add id :hbm_memory.RefreshPolicy/intervalNs (as-double (get data :intervalNs))]))
                   (cond-> (contains? data :temperatureC) (conj [:db/add id :hbm_memory.RefreshPolicy/temperatureC (as-double (get data :temperatureC))]))
                   (conj [:db/add id :hbm_memory.RefreshPolicy/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-refresh-policy
  "Delete a RefreshPolicy."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TestBin ────────────────────────────────────────────────────────────────
(defn create-test-bin
  "Create a TestBin."
  [port data]
  (require-fields data ["binCode" "yield"])
  (let [id (new-id "hbm_tes")
        e {:db/id id
           :hbm_memory.TestBin/id id
           :hbm_memory.TestBin/stackId (get data :stackId)
           :hbm_memory.TestBin/binCode (get data :binCode)
           :hbm_memory.TestBin/yield (as-double (get data :yield))
           :hbm_memory.TestBin/status (get data :status)
           :hbm_memory.TestBin/createdAt (now)
           :hbm_memory.TestBin/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-test-bins
  "List TestBin with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-test-bins port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :hbm_memory.TestBin/id))
         rows (apply-filters rows (:filter opts) [:hbm_memory.TestBin/stackId :hbm_memory.TestBin/binCode :hbm_memory.TestBin/yield :hbm_memory.TestBin/status])]
     (paginate rows opts))))

(defn get-test-bin
  "Retrieve a TestBin by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-test-bin port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-test-bin
  "Update a TestBin; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stackId) (conj [:db/add id :hbm_memory.TestBin/stackId (get data :stackId)]))
                   (cond-> (contains? data :binCode) (conj [:db/add id :hbm_memory.TestBin/binCode (get data :binCode)]))
                   (cond-> (contains? data :yield) (conj [:db/add id :hbm_memory.TestBin/yield (as-double (get data :yield))]))
                   (cond-> (contains? data :status) (conj [:db/add id :hbm_memory.TestBin/status (get data :status)]))
                   (conj [:db/add id :hbm_memory.TestBin/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-test-bin
  "Delete a TestBin."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/memorystacks" :op :create :entity "MemoryStack"}
   {:method "GET" :path "/v1/memorystacks" :op :list :entity "MemoryStack"}
   {:method "GET" :path "/v1/memorystacks/:id" :op :get :entity "MemoryStack"}
   {:method "PATCH" :path "/v1/memorystacks/:id" :op :update :entity "MemoryStack"}
   {:method "DELETE" :path "/v1/memorystacks/:id" :op :delete :entity "MemoryStack"}
   {:method "POST" :path "/v1/dramdies" :op :create :entity "DramDie"}
   {:method "GET" :path "/v1/dramdies" :op :list :entity "DramDie"}
   {:method "GET" :path "/v1/dramdies/:id" :op :get :entity "DramDie"}
   {:method "PATCH" :path "/v1/dramdies/:id" :op :update :entity "DramDie"}
   {:method "DELETE" :path "/v1/dramdies/:id" :op :delete :entity "DramDie"}
   {:method "POST" :path "/v1/throughsiliconvias" :op :create :entity "ThroughSiliconVia"}
   {:method "GET" :path "/v1/throughsiliconvias" :op :list :entity "ThroughSiliconVia"}
   {:method "GET" :path "/v1/throughsiliconvias/:id" :op :get :entity "ThroughSiliconVia"}
   {:method "PATCH" :path "/v1/throughsiliconvias/:id" :op :update :entity "ThroughSiliconVia"}
   {:method "DELETE" :path "/v1/throughsiliconvias/:id" :op :delete :entity "ThroughSiliconVia"}
   {:method "POST" :path "/v1/memorychannels" :op :create :entity "MemoryChannel"}
   {:method "GET" :path "/v1/memorychannels" :op :list :entity "MemoryChannel"}
   {:method "GET" :path "/v1/memorychannels/:id" :op :get :entity "MemoryChannel"}
   {:method "PATCH" :path "/v1/memorychannels/:id" :op :update :entity "MemoryChannel"}
   {:method "DELETE" :path "/v1/memorychannels/:id" :op :delete :entity "MemoryChannel"}
   {:method "POST" :path "/v1/refreshpolicies" :op :create :entity "RefreshPolicy"}
   {:method "GET" :path "/v1/refreshpolicies" :op :list :entity "RefreshPolicy"}
   {:method "GET" :path "/v1/refreshpolicies/:id" :op :get :entity "RefreshPolicy"}
   {:method "PATCH" :path "/v1/refreshpolicies/:id" :op :update :entity "RefreshPolicy"}
   {:method "DELETE" :path "/v1/refreshpolicies/:id" :op :delete :entity "RefreshPolicy"}
   {:method "POST" :path "/v1/testbins" :op :create :entity "TestBin"}
   {:method "GET" :path "/v1/testbins" :op :list :entity "TestBin"}
   {:method "GET" :path "/v1/testbins/:id" :op :get :entity "TestBin"}
   {:method "PATCH" :path "/v1/testbins/:id" :op :update :entity "TestBin"}
   {:method "DELETE" :path "/v1/testbins/:id" :op :delete :entity "TestBin"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"memorystacks" {:create create-memory-stack :list list-memory-stacks :get get-memory-stack :update update-memory-stack :delete delete-memory-stack}
   "dramdies" {:create create-dram-die :list list-dram-dies :get get-dram-die :update update-dram-die :delete delete-dram-die}
   "throughsiliconvias" {:create create-through-silicon-via :list list-through-silicon-vias :get get-through-silicon-via :update update-through-silicon-via :delete delete-through-silicon-via}
   "memorychannels" {:create create-memory-channel :list list-memory-channels :get get-memory-channel :update update-memory-channel :delete delete-memory-channel}
   "refreshpolicies" {:create create-refresh-policy :list list-refresh-policies :get get-refresh-policy :update update-refresh-policy :delete delete-refresh-policy}
   "testbins" {:create create-test-bin :list list-test-bins :get get-test-bin :update update-test-bin :delete delete-test-bin}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "hbm_memory-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
